import re
txt="The rain in Spain in the morning"
x=re.search("^The.*Spain$",txt)
print(x)
y=re.split("\s",txt)
print(y)
z=re.sub("\s","9",txt)
print(z)
s=re.search(r"\bS\w+",txt)
print(s.span())
p=re.compile('[a-k]')
print(p.findall("Aye,said Mr.Gibenson starck"))
k=re.compile('\d')
print(k.findall("I went to him at 11 AM on 4th"))
m=re.compile('\w')
print(m.findall("he said * in some_lang"))
n=re.compile('\w+')
print(n.findall("he said * in 11 AM  some_lang"))
print(re.sub('ub','~*','Subject has Uber booked already',flags = re.IGNORECASE))
print(re.escape("This is Awseome even 1 AM")) 
a=re.compile('\D')
print(a.findall("Hey bhargavi how are you 78 AM 11"))
b=re.compile('ab*') 
print(b.findall("ababbaabbb"))